<?php
require '../../../backend/config/db.php';
require '../../../backend/config/functions.php';
requireRole('principal');

// 1. CAPTURE FILTERS
$search = $_GET['search'] ?? '';
$action_filter = $_GET['action'] ?? '';
$start_date = $_GET['start_date'] ?? '';
$end_date = $_GET['end_date'] ?? '';

// 2. BUILD QUERY (LIMIT 100)
$sql = "SELECT a.*, u.first_name, u.last_name, u.role_id 
        FROM audit_log a
        LEFT JOIN user u ON a.user_id = u.user_id
        WHERE 1=1";

$params = [];

if (!empty($search)) {
    $sql .= " AND (u.first_name LIKE ? OR u.last_name LIKE ? OR a.user_action LIKE ?)";
    $term = "%$search%";
    array_push($params, $term, $term, $term);
}
if (!empty($action_filter)) {
    $sql .= " AND a.user_action = ?";
    $params[] = $action_filter;
}
if (!empty($start_date)) {
    $sql .= " AND a.timestamp >= ?";
    $params[] = "$start_date 00:00:00";
}
if (!empty($end_date)) {
    $sql .= " AND a.timestamp <= ?";
    $params[] = "$end_date 23:59:59";
}

$sql .= " ORDER BY a.timestamp DESC LIMIT 100"; // <--- LIMIT REQUIREMENT

$stmt = $pdo->prepare($sql);
$stmt->execute($params);
$logs = $stmt->fetchAll(PDO::FETCH_ASSOC);

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Audit Log Report</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; padding: 20px; }
        h2 { margin-bottom: 5px; }
        p { margin-top: 0; color: #555; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #333; padding: 8px; text-align: left; }
        th { background: #eee; }
        .footer { margin-top: 30px; text-align: right; font-style: italic; color: #555; }
        @media print { .no-print { display: none; } }
    </style>
</head>
<body onload="window.print()">

    <div class="no-print" style="margin-bottom:20px; text-align:right;">
        <button onclick="window.print()">Print Report</button>
        <button onclick="window.close()">Close</button>
    </div>

    <h2>System Audit Log Report</h2>
    <p>Generated on: <?= date('F d, Y h:i A') ?></p>
    <p>Filters: 
        <?= $action_filter ? "Action: $action_filter | " : "" ?>
        <?= $search ? "Search: $search | " : "" ?>
        Displaying last 100 matching records.
    </p>

    <table>
        <thead>
            <tr>
                <th>Time</th>
                <th>User</th>
                <th>Role</th>
                <th>Action</th>
                <th>IP Address</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($logs as $row): 
                $role = ($row['role_id'] == 1) ? 'Principal' : (($row['role_id'] == 2) ? 'Secretary' : 'Teacher');
            ?>
            <tr>
                <td><?= date('Y-m-d H:i:s', strtotime($row['timestamp'])) ?></td>
                <td><?= htmlspecialchars($row['last_name'] . ', ' . $row['first_name']) ?></td>
                <td><?= $role ?></td>
                <td><?= htmlspecialchars($row['user_action']) ?></td>
                <td><?= htmlspecialchars($row['ip_address']) ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <div class="footer">
        Generated by System Administrator
    </div>

</body>
</html>